services:
  # Backend Service
  - type: web
    name: restaurant-platform-backend
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    region: oregon
    branch: main
    healthCheckPath: /actuator/health
    numInstances: 1
    
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
      # Variables NO sensibles - OK en el archivo
      - key: JWT_EXPIRATION
        value: 86400000
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.com,http://localhost:3000
      - key: CORS_ALLOWED_METHODS
        value: GET,POST,PUT,DELETE,OPTIONS
      - key: CORS_ALLOWED_HEADERS
        value: "*"
      - key: CORS_ALLOW_CREDENTIALS
        value: true
      
      # VARIABLES SENSIBLES - Se configuran manualmente en Render Dashboard
      # NO incluir aquí por seguridad:
      # - POSTGRES_URL (se configura en Render Dashboard)
      # - POSTGRES_USER (se configura en Render Dashboard) 
      # - POSTGRES_PASSWORD (se configura en Render Dashboard)
      # - MONGODB_URI (se configura en Render Dashboard)
      # - JWT_SECRET (se configura en Render Dashboard)

# IMPORTANTE: Variables sensibles NO están en este archivo por seguridad
# Se configuran manualmente en Render Dashboard:
# 
# Variables a configurar en Render Dashboard → Environment:
# POSTGRES_URL = postgresql://restaurant_user:9cmOQBm33R42bsMuixjCaY3rhV6qvkP0@dpg-d35nj6ndiees738f6880-a.oregon-postgres.render.com/restaurant_reservation_db_qs5t
# POSTGRES_USER = restaurant_user
# POSTGRES_PASSWORD = 9cmOQBm33R42bsMuixjCaY3rhV6qvkP0
# MONGODB_URI = mongodb+srv://jose:1234@etm.nwysozv.mongodb.net/restaurant_db?retryWrites=true&w=majority&appName=ETM
# JWT_SECRET = super_secreto_jwt_para_produccion_render_2024_muy_seguro