# =======================================================================
# APPLICATION CONFIGURATION
# =======================================================================
spring:
  application:
    name: restaurant-reservation-platform
  profiles:
    active: ${ACTIVE_PROFILE:railway}
  jackson:
    serialization:
      fail-on-empty-beans: false

# =======================================================================
# SERVER CONFIGURATION
# =======================================================================
server:
  port: ${PORT:8080}

# =======================================================================
# LOGGING CONFIGURATION
# =======================================================================
logging:
  level:
    com.innova.restaurant: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# =======================================================================
# JWT CONFIGURATION
# =======================================================================
jwt:
  secret: mySecretKey123456789mySecretKey123456789mySecretKey123456789
  expiration: 86400000

---
# =======================================================================
# DEVELOPMENT PROFILE
# =======================================================================
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: restaurant_db

# Database Selection (jpa or mongo)
app:
  database:
    type: jpa

---
# =======================================================================
# PRODUCTION PROFILE
# =======================================================================
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL:${DB_URL:jdbc:postgresql://localhost:5432/restaurant_db}}
    username: ${POSTGRES_USER:${DB_USERNAME:postgres}}
    password: ${POSTGRES_PASSWORD:${DB_PASSWORD:password}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  data:
    mongodb:
      uri: ${MONGODB_ATLAS_URI:${MONGO_URI:mongodb://localhost:27017/restaurant_db}}

# Database Selection - Hybrid mode for production
app:
  database:
    type: hybrid

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:defaultSecretKey123456789defaultSecretKey123456789}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# Logging for Production
logging:
  level:
    com.innova.restaurant: INFO
    org.springframework.security: WARN

---
# =======================================================================
# PRODUCTION PROFILE (Alternative name for Railway)
# =======================================================================
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: ${DATABASE_URL:${DB_URL:jdbc:postgresql://localhost:5432/restaurant_db}}
    username: ${POSTGRES_USER:${DB_USERNAME:postgres}}
    password: ${POSTGRES_PASSWORD:${DB_PASSWORD:password}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  data:
    mongodb:
      uri: ${MONGODB_ATLAS_URI:${MONGO_URI:mongodb://localhost:27017/restaurant_db}}

# Database Selection - Hybrid mode for production
app:
  database:
    type: hybrid

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:defaultSecretKey123456789defaultSecretKey123456789}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# Logging for Production
logging:
  level:
    com.innova.restaurant: INFO
    org.springframework.security: WARN

---
# =======================================================================
# RAILWAY PROFILE (GitHub-safe version)
# =======================================================================
spring:
  config:
    activate:
      on-profile: railway
  datasource:
    url: ${DATABASE_URL:${RAILWAY_DB_URL:jdbc:postgresql://localhost:5432/restaurant_db}}
    username: ${POSTGRES_USER:${RAILWAY_DB_USERNAME:postgres}}
    password: ${POSTGRES_PASSWORD:${RAILWAY_DB_PASSWORD:password}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
  data:
    mongodb:
      uri: ${MONGODB_ATLAS_URI:${MONGODB_URI:mongodb://localhost:27017/restaurant_db}}

# Database Selection - Hybrid mode uses both
app:
  database:
    type: hybrid

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789mySecretKey123456789mySecretKey123456789}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# Logging for Railway
logging:
  level:
    com.innova.restaurant: INFO
    org.springframework.data.mongodb: WARN
    org.springframework.data.jpa: WARN

---
# =======================================================================
# TEST PROFILE
# =======================================================================
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    mongodb:
      database: test_restaurant_db

# Database Selection
app:
  database:
    type: jpa

# JWT for Testing
jwt:
  secret: testSecretKey123456789testSecretKey123456789testSecretKey123456789
  expiration: 3600000

---
# =======================================================================
# POSTGRES PROFILE
# =======================================================================
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/restaurant_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Database Selection
app:
  database:
    type: jpa

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:defaultSecretKey123456789defaultSecretKey123456789}
  expiration: ${JWT_EXPIRATION:86400000}

---
# =======================================================================
# MONGO PROFILE
# =======================================================================
spring:
  config:
    activate:
      on-profile: mongo
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/restaurant_db}
  # Configurar un datasource en memoria para JPA cuando usamos MongoDB
  datasource:
    url: jdbc:h2:mem:mongoMode
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

# Database Selection
app:
  database:
    type: mongo

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:defaultSecretKey123456789defaultSecretKey123456789}
  expiration: ${JWT_EXPIRATION:86400000}

---
# =======================================================================
# HYBRID PROFILE (PostgreSQL + MongoDB)
# =======================================================================
spring:
  config:
    activate:
      on-profile: hybrid
  # PostgreSQL Configuration
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/restaurant_reservation_db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  # MongoDB Configuration
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/restaurant_reservation_mongo}

# Database Selection - Hybrid mode uses both
app:
  database:
    type: hybrid

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# Logging for Hybrid Mode
logging:
  level:
    com.innova.restaurant: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.data.jpa: INFO